services:
  postgresql:
    image: postgres:15.3-alpine3.18
    container_name: postgres_db_2025
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESS_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
     - ${POSTGRES_PORT}:5432
    volumes:
     - ./postgres/data:/var/lib/postgresql/data
     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
     - appNet
     
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgresql
    networks:
     - appNet
     
  parkingapp:
    image: parkingapp2025
    container_name: parkingapp_container_2025
    restart: always
    ports:
      - "9090:8080"
      - "4848:4848"
    depends_on:
      - postgresql
    environment:
     DB_HOST: postgresql
     DB_PORT: 5432
     DB_NAME: ${POSTGRES_DB}
     DB_USER: ${POSTGRES_USER}
     DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
     - appNet

networks:
  appNet:

volumes:    
  pgadmin_data:
